import Foundation
import OverlayCore

public enum TouchLanguage: String {
    case english = "en"
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case japanese = "ja"

    public static func resolved(from locale: Locale) -> TouchLanguage {
        let identifier = locale.identifier.replacingOccurrences(of: "_", with: "-").lowercased()
        if identifier.hasPrefix("zh-hant") || identifier.hasPrefix("zh-tw") || identifier.hasPrefix("zh-hk") || identifier.hasPrefix("zh-mo") {
            return .traditionalChinese
        }
        if identifier.hasPrefix("zh") {
            return .simplifiedChinese
        }
        if identifier.hasPrefix("ja") {
            return .japanese
        }
        return .english
    }
}

public struct TouchLocalizer {
    public let language: TouchLanguage

    public init(language: TouchLanguage) {
        self.language = language
    }

    public init(locale: Locale) {
        self.init(language: .resolved(from: locale))
    }

    public func string(_ key: String) -> String {
        if let table = Self.tables[language.rawValue], let value = table[key] {
            return value
        }
        if let fallback = Self.tables[TouchLanguage.english.rawValue]?[key] {
            return fallback
        }
        return key
    }

    public func format(_ message: TouchMessage) -> String {
        let template = string(message.key)
        guard !message.arguments.isEmpty else { return template }
        var result = template
        for argument in message.arguments {
            if let range = result.range(of: "%@") {
                result = result.replacingCharacters(in: range, with: argument)
            }
        }
        return result
    }

    static let tables: [String: [String: String]] = [
        "en": english,
        "zh-Hans": simplifiedChinese,
        "zh-Hant": traditionalChinese,
        "ja": japanese
    ]

    private static let english: [String: String] = [
        "app.title": "DataLayer Studio",
        "status.chooseVideoAndFit": "Choose a video and a FIT/GPX file to start.",
        "status.loadingVideo": "Loading video %@…",
        "status.loadedVideo": "Loaded video %@.",
        "status.videoError": "Video error: %@",
        "status.loadingFit": "Loading activity %@…",
        "status.loadedFit": "Loaded activity %@.",
        "status.fitError": "Activity file error: %@",
        "status.sportStartSet": "Current frame (%@) is now the activity start.",
        "status.presetNameRequired": "Enter a preset name first.",
        "status.updatedPreset": "Updated preset “%@”.",
        "status.savedPreset": "Saved preset “%@”.",
        "status.appliedPreset": "Applied preset “%@”.",
        "status.deletedPreset": "Deleted preset “%@”.",
        "status.previewOverlayFailed": "Overlay preview failed: %@",
        "status.chooseFitFile": "Choose a FIT/GPX file before exporting.",
        "status.chooseVideoForCompositedExport": "Composited export needs a source video.",
        "status.outputSizeInvalid": "Output size must be even and between 2 and 16384.",
        "status.frameRateRange": "Frame rate must be between 1 and 240 fps.",
        "status.sourceDurationRange": "Export range must be at least 0.1 seconds.",
        "status.bitrateRange": "Bit rate must be between 1 and 1000000 kbps.",
        "status.checkOutputSettings": "Check the output settings.",
        "status.exporting": "Exporting…",
        "status.wroteFile": "Exported %@.",
        "status.exportCancelled": "Export cancelled.",
        "status.cancellingExport": "Cancelling export…",
        "status.exportError": "Export failed: %@",
        "status.exportNeedsSubscription": "Subscribe to export videos.",
        "subscription.state.unknown": "Checking subscription…",
        "subscription.state.trial": "Free trial active. Export is unlocked.",
        "subscription.state.active": "Subscription active. Export is unlocked.",
        "subscription.state.gracePeriod": "Billing grace period. Export stays unlocked.",
        "subscription.state.none": "Subscribe to export finished videos.",
        "subscription.restored": "Purchases restored.",
        "subscription.pending": "Purchase is pending approval.",
        "subscription.error": "Subscription error: %@",
        "common.cancel": "Cancel",
        "common.undo": "Undo",
        "common.redo": "Redo",
        "toolbar.sources": "Sources",
        "toolbar.inspector": "Inspector",
        "toolbar.settings": "Settings",
        "sources.title": "Sources",
        "sources.video": "Video",
        "sources.activity": "Activity (FIT/GPX)",
        "sources.chooseVideo": "Choose Video",
        "sources.chooseFromPhotos": "From Photos",
        "sources.chooseActivity": "Choose Activity File",
        "sources.retry": "Retry",
        "sources.videoEmptyHint": "Import the camera footage from Files or Photos.",
        "sources.activityEmptyHint": "Import the FIT/GPX recorded by your watch.",
        "sources.resolution": "Resolution",
        "sources.frameRate": "Frame rate",
        "sources.duration": "Duration",
        "sources.samples": "Samples",
        "sources.importingPhotosVideo": "Copying video from Photos…",
        "sources.photosImportFailed": "Could not import the selected Photos video.",
        "sync.title": "Sync",
        "sync.mode.offset": "Offset",
        "sync.mode.fitStart": "FIT start",
        "sync.mode.syncPoint": "Sync point",
        "sync.offsetSeconds": "Offset (s)",
        "sync.fitStartSeconds": "Video time at FIT start (s)",
        "sync.videoSeconds": "Video time (s)",
        "sync.fitSeconds": "FIT time (s)",
        "sync.markSportStart": "Set Current Frame as Activity Start",
        "presets.title": "Layout Presets",
        "presets.namePlaceholder": "Preset name",
        "presets.save": "Save",
        "presets.apply": "Apply",
        "presets.setDefault": "Set as Default",
        "presets.delete": "Delete",
        "presets.default": "Default",
        "presets.empty": "No presets yet. Presets sync with the Mac app via iCloud.",
        "presets.sync.localOnly": "Local only",
        "presets.sync.ready": "iCloud ready",
        "presets.sync.uploadRequested": "iCloud upload requested",
        "presets.sync.receivedUpdate": "Updated from iCloud",
        "export.title": "Export",
        "export.codec": "Codec",
        "export.resolution": "Resolution",
        "export.frameRate": "Frame rate",
        "export.bitrate": "Bit rate (kbps)",
        "export.range": "Export range",
        "export.rangeStart": "Start",
        "export.rangeEnd": "End",
        "export.useCurrentFrame": "Use current frame",
        "export.reset": "Reset",
        "export.start": "Export",
        "export.cancel": "Cancel Export",
        "export.eta": "About %@ left",
        "export.keepForeground": "Keep the app in the foreground while exporting.",
        "export.share": "Share",
        "export.saveToPhotos": "Save to Photos",
        "export.savedToPhotos": "Saved to Photos.",
        "export.saveToPhotosFailed": "Could not save to Photos: %@",
        "export.elapsed": "Finished in %@",
        "export.thermalWarning": "The device is hot. Export may slow down.",
        "export.custom": "Custom",
        "export.source": "Same as source",
        "export.width": "Width",
        "export.height": "Height",
        "export.inFiles": "Exports are saved to the DataLayer Studio folder in Files.",
        "paywall.title": "DataLayer Studio Mobile",
        "paywall.feature.export": "Edit and preview for free. Subscribe only when you are ready to export finished videos.",
        "paywall.trial.cta": "Start 7-Day Free Trial",
        "paywall.trial.terms": "Includes a 7-day free trial for eligible Apple accounts. After the trial, the subscription renews automatically at the selected monthly or yearly price until cancelled in App Store settings.",
        "paywall.subscribe.cta": "View Subscription",
        "paywall.restore": "Restore Purchases",
        "paywall.manage": "Manage Subscription",
        "paywall.redeem": "Redeem Code",
        "paywall.eula": "EULA",
        "paywall.privacy": "Privacy Policy",
        "canvas.emptyTitle": "Bring your ride or run to life",
        "canvas.emptyMessage": "Import a video and a FIT/GPX activity, sync them, then lay out data components on the canvas.",
        "timeline.play": "Play",
        "timeline.pause": "Pause",
        "timeline.stepBack": "Previous frame",
        "timeline.stepForward": "Next frame",
        "inspector.title": "Inspector",
        "inspector.noSelection": "Select a component on the canvas.",
        "inspector.visible": "Visible",
        "inspector.scale": "Scale",
        "inspector.textScale": "Text scale",
        "inspector.panelOpacity": "Panel opacity",
        "inspector.width": "Width",
        "inspector.height": "Height",
        "inspector.showFill": "Show fill",
        "inspector.showGrid": "Show grid",
        "inspector.showCursor": "Show cursor",
        "inspector.showMinMax": "Show min/max",
        "inspector.showDistanceLabels": "Show distance labels",
        "inspector.accent": "Accent color",
        "inspector.accent.global": "Global",
        "inspector.showsPanel": "Show panel",
        "inspector.showsLabel": "Show label",
        "inspector.showsUnit": "Show unit",
        "inspector.precision": "Decimals",
        "inspector.layerForward": "Bring forward",
        "inspector.layerBackward": "Send backward",
        "inspector.duplicate": "Duplicate",
        "inspector.delete": "Delete",
        "inspector.addComponent": "Add Component",
        "inspector.position": "Position",
        "inspector.appearance": "Appearance",
        "inspector.content": "Content",
        "settings.title": "Settings",
        "settings.unit": "Distance unit",
        "settings.subscription": "Subscription",
        "unit.kilometers": "Kilometers",
        "unit.meters": "Meters",
        "accent.telemetryGreen": "Telemetry green",
        "accent.electricBlue": "Electric blue",
        "accent.amber": "Amber",
        "accent.hotRed": "Hot red",
        "accent.cleanWhite": "Clean white",
        "component.speed": "Speed",
        "component.pace": "Pace",
        "component.heartRate": "Heart rate",
        "component.cadence": "Cadence",
        "component.calories": "Calories",
        "component.ascent": "Ascent",
        "component.strideLength": "Stride length",
        "component.power": "Power",
        "component.verticalOscillation": "Vertical oscillation",
        "component.groundContactTime": "Ground contact time",
        "component.groundContactTimePercent": "Ground contact %",
        "component.groundContactTimeBalance": "Ground contact balance",
        "component.verticalRatio": "Vertical ratio",
        "component.respirationRate": "Respiration rate",
        "component.stepSpeedLoss": "Step speed loss %",
        "component.formPower": "Form power",
        "component.airPower": "Air power",
        "component.legSpringStiffness": "Leg spring stiffness",
        "component.weather": "Weather",
        "component.distance": "Distance value",
        "component.route": "GPS route",
        "component.altitudeProfile": "Altitude profile",
        "component.topProgress": "Distance progress",
        "component.timeDate": "Time & date"
    ]

    private static let simplifiedChinese: [String: String] = [
        "app.title": "DataLayer Studio",
        "status.chooseVideoAndFit": "先选择视频和 FIT/GPX 文件。",
        "status.loadingVideo": "正在载入视频 %@…",
        "status.loadedVideo": "已载入视频 %@。",
        "status.videoError": "视频错误：%@",
        "status.loadingFit": "正在载入活动文件 %@…",
        "status.loadedFit": "已载入活动文件 %@。",
        "status.fitError": "活动文件错误：%@",
        "status.sportStartSet": "已将当前帧（%@）设为运动开始。",
        "status.presetNameRequired": "请先输入预设名称。",
        "status.updatedPreset": "已更新预设“%@”。",
        "status.savedPreset": "已保存预设“%@”。",
        "status.appliedPreset": "已套用预设“%@”。",
        "status.deletedPreset": "已删除预设“%@”。",
        "status.previewOverlayFailed": "浮层预览失败：%@",
        "status.chooseFitFile": "导出前请先选择 FIT/GPX 文件。",
        "status.chooseVideoForCompositedExport": "合成导出需要源视频。",
        "status.outputSizeInvalid": "输出尺寸必须是 2–16384 之间的偶数。",
        "status.frameRateRange": "帧率必须在 1–240 fps 之间。",
        "status.sourceDurationRange": "导出区间至少 0.1 秒。",
        "status.bitrateRange": "码率必须在 1–1000000 kbps 之间。",
        "status.checkOutputSettings": "请检查输出设置。",
        "status.exporting": "正在导出…",
        "status.wroteFile": "已导出 %@。",
        "status.exportCancelled": "已取消导出。",
        "status.cancellingExport": "正在取消导出…",
        "status.exportError": "导出失败：%@",
        "status.exportNeedsSubscription": "订阅后即可导出视频。",
        "subscription.state.unknown": "正在检查订阅…",
        "subscription.state.trial": "免费试用中，已解锁导出。",
        "subscription.state.active": "订阅有效，已解锁导出。",
        "subscription.state.gracePeriod": "账单宽限期内，导出保持解锁。",
        "subscription.state.none": "订阅后可导出成片视频。",
        "subscription.restored": "已恢复购买。",
        "subscription.pending": "购买正在等待批准。",
        "subscription.error": "订阅错误：%@",
        "common.cancel": "取消",
        "common.undo": "撤销",
        "common.redo": "重做",
        "toolbar.sources": "素材面板",
        "toolbar.inspector": "检查器",
        "toolbar.settings": "设置",
        "sources.title": "素材",
        "sources.video": "视频",
        "sources.activity": "活动文件（FIT/GPX）",
        "sources.chooseVideo": "选择视频",
        "sources.chooseFromPhotos": "从照片选择",
        "sources.chooseActivity": "选择活动文件",
        "sources.retry": "重试",
        "sources.videoEmptyHint": "从「文件」或「照片」导入相机视频。",
        "sources.activityEmptyHint": "导入手表记录的 FIT/GPX 文件。",
        "sources.resolution": "分辨率",
        "sources.frameRate": "帧率",
        "sources.duration": "时长",
        "sources.samples": "样本数",
        "sources.importingPhotosVideo": "正在从照片拷贝视频…",
        "sources.photosImportFailed": "无法导入所选的照片视频。",
        "sync.title": "对表",
        "sync.mode.offset": "偏移",
        "sync.mode.fitStart": "FIT 起点",
        "sync.mode.syncPoint": "打点对齐",
        "sync.offsetSeconds": "偏移（秒）",
        "sync.fitStartSeconds": "FIT 起点对应视频时间（秒）",
        "sync.videoSeconds": "视频时间（秒）",
        "sync.fitSeconds": "FIT 时间（秒）",
        "sync.markSportStart": "将当前帧设为运动开始",
        "presets.title": "布局预设",
        "presets.namePlaceholder": "预设名称",
        "presets.save": "保存",
        "presets.apply": "套用",
        "presets.setDefault": "设为默认",
        "presets.delete": "删除",
        "presets.default": "默认",
        "presets.empty": "还没有预设。预设会通过 iCloud 与 Mac 版同步。",
        "presets.sync.localOnly": "仅本机",
        "presets.sync.ready": "iCloud 就绪",
        "presets.sync.uploadRequested": "已请求上传 iCloud",
        "presets.sync.receivedUpdate": "已收到 iCloud 更新",
        "export.title": "导出",
        "export.codec": "编码",
        "export.resolution": "分辨率",
        "export.frameRate": "帧率",
        "export.bitrate": "码率（kbps）",
        "export.range": "导出区间",
        "export.rangeStart": "开始",
        "export.rangeEnd": "结束",
        "export.useCurrentFrame": "用当前帧",
        "export.reset": "重置",
        "export.start": "导出",
        "export.cancel": "取消导出",
        "export.eta": "剩余约 %@",
        "export.keepForeground": "导出期间请保持 App 在前台。",
        "export.share": "分享",
        "export.saveToPhotos": "存入照片",
        "export.savedToPhotos": "已存入照片。",
        "export.saveToPhotosFailed": "无法存入照片：%@",
        "export.elapsed": "用时 %@",
        "export.thermalWarning": "设备温度较高，导出可能变慢。",
        "export.custom": "自定义",
        "export.source": "与源一致",
        "export.width": "宽",
        "export.height": "高",
        "export.inFiles": "导出文件保存在「文件」App 的 DataLayer Studio 目录。",
        "paywall.title": "DataLayer Studio Mobile",
        "paywall.feature.export": "编辑和预览免费开放。只有准备导出成片时才需要订阅。",
        "paywall.trial.cta": "开始 7 天免费试用",
        "paywall.trial.terms": "符合资格的 Apple 账户可享 7 天免费试用。试用结束后，订阅会按所选月付或年付价格自动续订，直到你在 App Store 设置中取消。",
        "paywall.subscribe.cta": "查看订阅",
        "paywall.restore": "恢复购买",
        "paywall.manage": "管理订阅",
        "paywall.redeem": "兑换代码",
        "paywall.eula": "EULA",
        "paywall.privacy": "隐私政策",
        "canvas.emptyTitle": "让骑行与跑步数据跃然片上",
        "canvas.emptyMessage": "导入视频和 FIT/GPX 活动文件，完成对表后即可在画布上排布数据组件。",
        "timeline.play": "播放",
        "timeline.pause": "暂停",
        "timeline.stepBack": "上一帧",
        "timeline.stepForward": "下一帧",
        "inspector.title": "检查器",
        "inspector.noSelection": "在画布上选中一个组件。",
        "inspector.visible": "显示",
        "inspector.scale": "缩放",
        "inspector.textScale": "文字缩放",
        "inspector.panelOpacity": "面板不透明度",
        "inspector.width": "宽度",
        "inspector.height": "高度",
        "inspector.showFill": "显示填充",
        "inspector.showGrid": "显示网格",
        "inspector.showCursor": "显示当前位置",
        "inspector.showMinMax": "显示最高/最低",
        "inspector.showDistanceLabels": "显示距离标签",
        "inspector.accent": "强调色",
        "inspector.accent.global": "跟随全局",
        "inspector.showsPanel": "显示面板",
        "inspector.showsLabel": "显示标签",
        "inspector.showsUnit": "显示单位",
        "inspector.precision": "小数位",
        "inspector.layerForward": "上移一层",
        "inspector.layerBackward": "下移一层",
        "inspector.duplicate": "复制",
        "inspector.delete": "删除",
        "inspector.addComponent": "添加组件",
        "inspector.position": "位置",
        "inspector.appearance": "外观",
        "inspector.content": "内容",
        "settings.title": "设置",
        "settings.unit": "距离单位",
        "settings.subscription": "订阅",
        "unit.kilometers": "公里",
        "unit.meters": "米",
        "accent.telemetryGreen": "遥测绿",
        "accent.electricBlue": "电光蓝",
        "accent.amber": "琥珀",
        "accent.hotRed": "炽热红",
        "accent.cleanWhite": "纯净白",
        "component.speed": "速度",
        "component.pace": "配速",
        "component.heartRate": "心率",
        "component.cadence": "步频",
        "component.calories": "卡路里",
        "component.ascent": "累计爬升",
        "component.strideLength": "步幅",
        "component.power": "功率",
        "component.verticalOscillation": "垂直振幅",
        "component.groundContactTime": "触地时间",
        "component.groundContactTimePercent": "触地时间占比",
        "component.groundContactTimeBalance": "触地平衡",
        "component.verticalRatio": "垂直步幅比",
        "component.respirationRate": "呼吸率",
        "component.stepSpeedLoss": "步速损失",
        "component.formPower": "姿态功率",
        "component.airPower": "腾空功率",
        "component.legSpringStiffness": "腿部弹簧刚度",
        "component.weather": "天气",
        "component.distance": "距离数值",
        "component.route": "GPS 路线",
        "component.altitudeProfile": "海拔剖面",
        "component.topProgress": "距离进度条",
        "component.timeDate": "时间与日期"
    ]

    private static let traditionalChinese: [String: String] = [
        "app.title": "DataLayer Studio",
        "status.chooseVideoAndFit": "先選擇影片和 FIT/GPX 檔案。",
        "status.loadingVideo": "正在載入影片 %@…",
        "status.loadedVideo": "已載入影片 %@。",
        "status.videoError": "影片錯誤：%@",
        "status.loadingFit": "正在載入活動檔案 %@…",
        "status.loadedFit": "已載入活動檔案 %@。",
        "status.fitError": "活動檔案錯誤：%@",
        "status.sportStartSet": "已將目前影格（%@）設為運動開始。",
        "status.presetNameRequired": "請先輸入預設組名稱。",
        "status.updatedPreset": "已更新預設組「%@」。",
        "status.savedPreset": "已儲存預設組「%@」。",
        "status.appliedPreset": "已套用預設組「%@」。",
        "status.deletedPreset": "已刪除預設組「%@」。",
        "status.previewOverlayFailed": "浮層預覽失敗：%@",
        "status.chooseFitFile": "匯出前請先選擇 FIT/GPX 檔案。",
        "status.chooseVideoForCompositedExport": "合成匯出需要來源影片。",
        "status.outputSizeInvalid": "輸出尺寸必須是 2–16384 之間的偶數。",
        "status.frameRateRange": "影格率必須在 1–240 fps 之間。",
        "status.sourceDurationRange": "匯出區間至少 0.1 秒。",
        "status.bitrateRange": "位元率必須在 1–1000000 kbps 之間。",
        "status.checkOutputSettings": "請檢查輸出設定。",
        "status.exporting": "正在匯出…",
        "status.wroteFile": "已匯出 %@。",
        "status.exportCancelled": "已取消匯出。",
        "status.cancellingExport": "正在取消匯出…",
        "status.exportError": "匯出失敗：%@",
        "status.exportNeedsSubscription": "訂閱後即可匯出影片。",
        "subscription.state.unknown": "正在檢查訂閱…",
        "subscription.state.trial": "免費試用中，已解鎖匯出。",
        "subscription.state.active": "訂閱有效，已解鎖匯出。",
        "subscription.state.gracePeriod": "帳單寬限期內，匯出保持解鎖。",
        "subscription.state.none": "訂閱後可匯出成片影片。",
        "subscription.restored": "已恢復購買。",
        "subscription.pending": "購買正在等待核准。",
        "subscription.error": "訂閱錯誤：%@",
        "common.cancel": "取消",
        "common.undo": "還原",
        "common.redo": "重做",
        "toolbar.sources": "素材面板",
        "toolbar.inspector": "檢查器",
        "toolbar.settings": "設定",
        "sources.title": "素材",
        "sources.video": "影片",
        "sources.activity": "活動檔案（FIT/GPX）",
        "sources.chooseVideo": "選擇影片",
        "sources.chooseFromPhotos": "從照片選擇",
        "sources.chooseActivity": "選擇活動檔案",
        "sources.retry": "重試",
        "sources.videoEmptyHint": "從「檔案」或「照片」匯入相機影片。",
        "sources.activityEmptyHint": "匯入手錶記錄的 FIT/GPX 檔案。",
        "sources.resolution": "解析度",
        "sources.frameRate": "影格率",
        "sources.duration": "時長",
        "sources.samples": "樣本數",
        "sources.importingPhotosVideo": "正在從照片拷貝影片…",
        "sources.photosImportFailed": "無法匯入所選的照片影片。",
        "sync.title": "對錶",
        "sync.mode.offset": "偏移",
        "sync.mode.fitStart": "FIT 起點",
        "sync.mode.syncPoint": "打點對齊",
        "sync.offsetSeconds": "偏移（秒）",
        "sync.fitStartSeconds": "FIT 起點對應影片時間（秒）",
        "sync.videoSeconds": "影片時間（秒）",
        "sync.fitSeconds": "FIT 時間（秒）",
        "sync.markSportStart": "將目前影格設為運動開始",
        "presets.title": "版面預設組",
        "presets.namePlaceholder": "預設組名稱",
        "presets.save": "儲存",
        "presets.apply": "套用",
        "presets.setDefault": "設為預設",
        "presets.delete": "刪除",
        "presets.default": "預設",
        "presets.empty": "尚無預設組。預設組會透過 iCloud 與 Mac 版同步。",
        "presets.sync.localOnly": "僅本機",
        "presets.sync.ready": "iCloud 就緒",
        "presets.sync.uploadRequested": "已要求上傳 iCloud",
        "presets.sync.receivedUpdate": "已收到 iCloud 更新",
        "export.title": "匯出",
        "export.codec": "編碼",
        "export.resolution": "解析度",
        "export.frameRate": "影格率",
        "export.bitrate": "位元率（kbps）",
        "export.range": "匯出區間",
        "export.rangeStart": "開始",
        "export.rangeEnd": "結束",
        "export.useCurrentFrame": "用目前影格",
        "export.reset": "重設",
        "export.start": "匯出",
        "export.cancel": "取消匯出",
        "export.eta": "剩餘約 %@",
        "export.keepForeground": "匯出期間請讓 App 保持在前台。",
        "export.share": "分享",
        "export.saveToPhotos": "儲存到照片",
        "export.savedToPhotos": "已儲存到照片。",
        "export.saveToPhotosFailed": "無法儲存到照片：%@",
        "export.elapsed": "耗時 %@",
        "export.thermalWarning": "裝置溫度較高，匯出可能變慢。",
        "export.custom": "自訂",
        "export.source": "與來源一致",
        "export.width": "寬",
        "export.height": "高",
        "export.inFiles": "匯出檔案儲存在「檔案」App 的 DataLayer Studio 目錄。",
        "paywall.title": "DataLayer Studio Mobile",
        "paywall.feature.export": "編輯和預覽免費開放。只有準備匯出成片時才需要訂閱。",
        "paywall.trial.cta": "開始 7 天免費試用",
        "paywall.trial.terms": "符合資格的 Apple 帳號可享 7 天免費試用。試用結束後，訂閱會按所選月付或年付價格自動續訂，直到你在 App Store 設定中取消。",
        "paywall.subscribe.cta": "查看訂閱",
        "paywall.restore": "恢復購買",
        "paywall.manage": "管理訂閱",
        "paywall.redeem": "兌換代碼",
        "paywall.eula": "EULA",
        "paywall.privacy": "隱私權政策",
        "canvas.emptyTitle": "讓騎行與跑步數據躍然片上",
        "canvas.emptyMessage": "匯入影片和 FIT/GPX 活動檔案，完成對錶後即可在畫布上排列數據元件。",
        "timeline.play": "播放",
        "timeline.pause": "暫停",
        "timeline.stepBack": "上一影格",
        "timeline.stepForward": "下一影格",
        "inspector.title": "檢查器",
        "inspector.noSelection": "在畫布上選取一個元件。",
        "inspector.visible": "顯示",
        "inspector.scale": "縮放",
        "inspector.textScale": "文字縮放",
        "inspector.panelOpacity": "面板不透明度",
        "inspector.width": "寬度",
        "inspector.height": "高度",
        "inspector.showFill": "顯示填色",
        "inspector.showGrid": "顯示網格",
        "inspector.showCursor": "顯示目前位置",
        "inspector.showMinMax": "顯示最高／最低",
        "inspector.showDistanceLabels": "顯示距離標籤",
        "inspector.accent": "強調色",
        "inspector.accent.global": "跟隨全域",
        "inspector.showsPanel": "顯示面板",
        "inspector.showsLabel": "顯示標籤",
        "inspector.showsUnit": "顯示單位",
        "inspector.precision": "小數位",
        "inspector.layerForward": "上移一層",
        "inspector.layerBackward": "下移一層",
        "inspector.duplicate": "複製",
        "inspector.delete": "刪除",
        "inspector.addComponent": "加入元件",
        "inspector.position": "位置",
        "inspector.appearance": "外觀",
        "inspector.content": "內容",
        "settings.title": "設定",
        "settings.unit": "距離單位",
        "settings.subscription": "訂閱",
        "unit.kilometers": "公里",
        "unit.meters": "公尺",
        "accent.telemetryGreen": "遙測綠",
        "accent.electricBlue": "電光藍",
        "accent.amber": "琥珀",
        "accent.hotRed": "熾熱紅",
        "accent.cleanWhite": "純淨白",
        "component.speed": "速度",
        "component.pace": "配速",
        "component.heartRate": "心率",
        "component.cadence": "步頻",
        "component.calories": "卡路里",
        "component.ascent": "累計爬升",
        "component.strideLength": "步幅",
        "component.power": "功率",
        "component.verticalOscillation": "垂直振幅",
        "component.groundContactTime": "觸地時間",
        "component.groundContactTimePercent": "觸地時間佔比",
        "component.groundContactTimeBalance": "觸地平衡",
        "component.verticalRatio": "垂直步幅比",
        "component.respirationRate": "呼吸率",
        "component.stepSpeedLoss": "步速損失",
        "component.formPower": "姿態功率",
        "component.airPower": "騰空功率",
        "component.legSpringStiffness": "腿部彈簧剛度",
        "component.weather": "天氣",
        "component.distance": "距離數值",
        "component.route": "GPS 路線",
        "component.altitudeProfile": "海拔剖面",
        "component.topProgress": "距離進度條",
        "component.timeDate": "時間與日期"
    ]

    private static let japanese: [String: String] = [
        "app.title": "DataLayer Studio",
        "status.chooseVideoAndFit": "動画と FIT/GPX ファイルを選択してください。",
        "status.loadingVideo": "動画 %@ を読み込み中…",
        "status.loadedVideo": "動画 %@ を読み込みました。",
        "status.videoError": "動画エラー：%@",
        "status.loadingFit": "アクティビティ %@ を読み込み中…",
        "status.loadedFit": "アクティビティ %@ を読み込みました。",
        "status.fitError": "アクティビティファイルエラー：%@",
        "status.sportStartSet": "現在のフレーム（%@）を運動開始に設定しました。",
        "status.presetNameRequired": "プリセット名を入力してください。",
        "status.updatedPreset": "プリセット「%@」を更新しました。",
        "status.savedPreset": "プリセット「%@」を保存しました。",
        "status.appliedPreset": "プリセット「%@」を適用しました。",
        "status.deletedPreset": "プリセット「%@」を削除しました。",
        "status.previewOverlayFailed": "オーバーレイプレビューに失敗：%@",
        "status.chooseFitFile": "書き出す前に FIT/GPX ファイルを選択してください。",
        "status.chooseVideoForCompositedExport": "合成書き出しには元動画が必要です。",
        "status.outputSizeInvalid": "出力サイズは 2〜16384 の偶数にしてください。",
        "status.frameRateRange": "フレームレートは 1〜240 fps にしてください。",
        "status.sourceDurationRange": "書き出し範囲は 0.1 秒以上必要です。",
        "status.bitrateRange": "ビットレートは 1〜1000000 kbps にしてください。",
        "status.checkOutputSettings": "出力設定を確認してください。",
        "status.exporting": "書き出し中…",
        "status.wroteFile": "%@ を書き出しました。",
        "status.exportCancelled": "書き出しをキャンセルしました。",
        "status.cancellingExport": "書き出しをキャンセル中…",
        "status.exportError": "書き出しに失敗：%@",
        "status.exportNeedsSubscription": "動画を書き出すにはサブスクリプションが必要です。",
        "subscription.state.unknown": "サブスクリプションを確認中…",
        "subscription.state.trial": "無料トライアル中です。書き出しは利用できます。",
        "subscription.state.active": "サブスクリプションは有効です。書き出しは利用できます。",
        "subscription.state.gracePeriod": "請求の猶予期間中です。書き出しは利用できます。",
        "subscription.state.none": "完成動画を書き出すには登録してください。",
        "subscription.restored": "購入を復元しました。",
        "subscription.pending": "購入は承認待ちです。",
        "subscription.error": "サブスクリプションエラー：%@",
        "common.cancel": "キャンセル",
        "common.undo": "取り消す",
        "common.redo": "やり直す",
        "toolbar.sources": "ソースパネル",
        "toolbar.inspector": "インスペクタ",
        "toolbar.settings": "設定",
        "sources.title": "ソース",
        "sources.video": "動画",
        "sources.activity": "アクティビティ（FIT/GPX）",
        "sources.chooseVideo": "動画を選択",
        "sources.chooseFromPhotos": "写真から選択",
        "sources.chooseActivity": "アクティビティを選択",
        "sources.retry": "再試行",
        "sources.videoEmptyHint": "「ファイル」または「写真」からカメラ動画を読み込みます。",
        "sources.activityEmptyHint": "ウォッチで記録した FIT/GPX を読み込みます。",
        "sources.resolution": "解像度",
        "sources.frameRate": "フレームレート",
        "sources.duration": "長さ",
        "sources.samples": "サンプル数",
        "sources.importingPhotosVideo": "写真から動画をコピー中…",
        "sources.photosImportFailed": "選択した写真の動画を読み込めませんでした。",
        "sync.title": "同期",
        "sync.mode.offset": "オフセット",
        "sync.mode.fitStart": "FIT 開始",
        "sync.mode.syncPoint": "同期ポイント",
        "sync.offsetSeconds": "オフセット（秒）",
        "sync.fitStartSeconds": "FIT 開始の動画時間（秒）",
        "sync.videoSeconds": "動画時間（秒）",
        "sync.fitSeconds": "FIT 時間（秒）",
        "sync.markSportStart": "現在のフレームを運動開始に設定",
        "presets.title": "レイアウトプリセット",
        "presets.namePlaceholder": "プリセット名",
        "presets.save": "保存",
        "presets.apply": "適用",
        "presets.setDefault": "デフォルトに設定",
        "presets.delete": "削除",
        "presets.default": "デフォルト",
        "presets.empty": "プリセットはまだありません。iCloud で Mac 版と同期されます。",
        "presets.sync.localOnly": "ローカルのみ",
        "presets.sync.ready": "iCloud 準備完了",
        "presets.sync.uploadRequested": "iCloud アップロード要求済み",
        "presets.sync.receivedUpdate": "iCloud から更新を受信",
        "export.title": "書き出し",
        "export.codec": "コーデック",
        "export.resolution": "解像度",
        "export.frameRate": "フレームレート",
        "export.bitrate": "ビットレート（kbps）",
        "export.range": "書き出し範囲",
        "export.rangeStart": "開始",
        "export.rangeEnd": "終了",
        "export.useCurrentFrame": "現在のフレームを使用",
        "export.reset": "リセット",
        "export.start": "書き出す",
        "export.cancel": "書き出しをキャンセル",
        "export.eta": "残り約 %@",
        "export.keepForeground": "書き出し中はアプリを前面に保ってください。",
        "export.share": "共有",
        "export.saveToPhotos": "写真に保存",
        "export.savedToPhotos": "写真に保存しました。",
        "export.saveToPhotosFailed": "写真に保存できませんでした：%@",
        "export.elapsed": "所要時間 %@",
        "export.thermalWarning": "デバイスが高温です。書き出しが遅くなる場合があります。",
        "export.custom": "カスタム",
        "export.source": "ソースと同じ",
        "export.width": "幅",
        "export.height": "高さ",
        "export.inFiles": "書き出したファイルは「ファイル」App の DataLayer Studio フォルダに保存されます。",
        "paywall.title": "DataLayer Studio Mobile",
        "paywall.feature.export": "編集とプレビューは無料です。完成動画を書き出すときだけサブスクリプションが必要です。",
        "paywall.trial.cta": "7日間無料トライアルを開始",
        "paywall.trial.terms": "対象の Apple アカウントは 7 日間無料で試用できます。試用後は、選択した月額または年額プランで自動更新され、App Store 設定でキャンセルするまで継続します。",
        "paywall.subscribe.cta": "サブスクリプションを見る",
        "paywall.restore": "購入を復元",
        "paywall.manage": "サブスクリプションを管理",
        "paywall.redeem": "コードを使う",
        "paywall.eula": "EULA",
        "paywall.privacy": "プライバシーポリシー",
        "canvas.emptyTitle": "ライドとランのデータを映像に",
        "canvas.emptyMessage": "動画と FIT/GPX を読み込み、同期したらキャンバスにデータコンポーネントを配置できます。",
        "timeline.play": "再生",
        "timeline.pause": "一時停止",
        "timeline.stepBack": "前のフレーム",
        "timeline.stepForward": "次のフレーム",
        "inspector.title": "インスペクタ",
        "inspector.noSelection": "キャンバスでコンポーネントを選択してください。",
        "inspector.visible": "表示",
        "inspector.scale": "拡大率",
        "inspector.textScale": "文字サイズ",
        "inspector.panelOpacity": "パネル不透明度",
        "inspector.width": "幅",
        "inspector.height": "高さ",
        "inspector.showFill": "塗りを表示",
        "inspector.showGrid": "グリッドを表示",
        "inspector.showCursor": "現在位置を表示",
        "inspector.showMinMax": "最高／最低を表示",
        "inspector.showDistanceLabels": "距離ラベルを表示",
        "inspector.accent": "アクセントカラー",
        "inspector.accent.global": "グローバルに従う",
        "inspector.showsPanel": "パネルを表示",
        "inspector.showsLabel": "ラベルを表示",
        "inspector.showsUnit": "単位を表示",
        "inspector.precision": "小数点以下",
        "inspector.layerForward": "前面へ",
        "inspector.layerBackward": "背面へ",
        "inspector.duplicate": "複製",
        "inspector.delete": "削除",
        "inspector.addComponent": "コンポーネントを追加",
        "inspector.position": "位置",
        "inspector.appearance": "外観",
        "inspector.content": "コンテンツ",
        "settings.title": "設定",
        "settings.unit": "距離単位",
        "settings.subscription": "サブスクリプション",
        "unit.kilometers": "キロメートル",
        "unit.meters": "メートル",
        "accent.telemetryGreen": "テレメトリーグリーン",
        "accent.electricBlue": "エレクトリックブルー",
        "accent.amber": "アンバー",
        "accent.hotRed": "ホットレッド",
        "accent.cleanWhite": "クリーンホワイト",
        "component.speed": "スピード",
        "component.pace": "ペース",
        "component.heartRate": "心拍数",
        "component.cadence": "ケイデンス",
        "component.calories": "カロリー",
        "component.ascent": "累積上昇",
        "component.strideLength": "ストライド",
        "component.power": "パワー",
        "component.verticalOscillation": "上下動",
        "component.groundContactTime": "接地時間",
        "component.groundContactTimePercent": "接地時間率",
        "component.groundContactTimeBalance": "接地バランス",
        "component.verticalRatio": "上下動率",
        "component.respirationRate": "呼吸数",
        "component.stepSpeedLoss": "ステップ速度損失",
        "component.formPower": "フォームパワー",
        "component.airPower": "エアパワー",
        "component.legSpringStiffness": "脚バネ剛性",
        "component.weather": "天気",
        "component.distance": "距離",
        "component.route": "GPS ルート",
        "component.altitudeProfile": "高度プロファイル",
        "component.topProgress": "距離プログレス",
        "component.timeDate": "時刻と日付"
    ]
}

public extension OverlayComponentID {
    var localizationKey: String {
        "component.\(rawValue)"
    }

    var touchSystemImage: String {
        switch self {
        case .speed:
            return "gauge.with.dots.needle.bottom.50percent"
        case .pace:
            return "timer"
        case .heartRate:
            return "heart.fill"
        case .cadence:
            return "figure.run"
        case .calories:
            return "flame.fill"
        case .ascent:
            return "mountain.2.fill"
        case .strideLength:
            return "arrow.left.and.right"
        case .power:
            return "bolt.fill"
        case .verticalOscillation:
            return "arrow.up.and.down"
        case .groundContactTime:
            return "timer"
        case .groundContactTimePercent:
            return "percent"
        case .groundContactTimeBalance:
            return "scalemass"
        case .verticalRatio:
            return "arrow.up.and.down"
        case .respirationRate:
            return "lungs.fill"
        case .stepSpeedLoss:
            return "speedometer"
        case .formPower:
            return "bolt.badge.clock"
        case .airPower:
            return "wind"
        case .legSpringStiffness:
            return "arrow.up.and.down"
        case .weather:
            return "cloud.sun.fill"
        case .distance:
            return "ruler"
        case .route:
            return "point.topleft.down.curvedto.point.bottomright.up"
        case .altitudeProfile:
            return "mountain.2"
        case .topProgress:
            return "chart.bar.xaxis"
        case .timeDate:
            return "clock"
        }
    }
}

public extension OverlayAccentColor {
    var localizationKey: String {
        "accent.\(rawValue)"
    }
}
